my_string = input("fisting is?: ")
print(my_string .replace("Fisting", "anal"))
print(my_string .replace(" ", ""))
print(len(my_string))
print(my_string .upper())
print(my_string .lower())
print(my_string[0])
print(my_string[-1])